[colors]
foreground = "#365fa6"
background = "#ffffff"
cursor_bg = "#365fa6"
cursor_border = "#365fa6"
cursor_fg = "#ffffff"
selection_bg = "#c2caf1"
selection_fg = "#365fa6"

ansi = ["#ffffff", "#ff053b", "#2f5f0d", "#815b00", "#0078e9", "#9f46ff", "#18687a", "#555f8d"]
brights = ["#9ea2c5", "#ff053b", "#2f5f0d", "#815b00", "#0078e9", "#9f46ff", "#18687a", "#365fa6"]

[colors.tab_bar]
inactive_tab_edge = "#ededf2"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#0078e9"
bg_color = "#ffffff"

[colors.tab_bar.inactive_tab]
bg_color = "#ededf2"
fg_color = "#8990b3"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#ededf2"
fg_color = "#0078e9"

[colors.tab_bar.new_tab_hover]
fg_color = "#ededf2"
bg_color = "#0078e9"

[colors.tab_bar.new_tab]
fg_color = "#0078e9"
bg_color = "#191b28"

[metadata]
aliases = []
author = "folke"
name = "Tokyo Night Day"