[colors]
foreground = "#c0caf5"
background = "#000000"
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#000000"
selection_bg = "#182440"
selection_fg = "#c0caf5"

ansi = ["#000000", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#a9b1d6"]
brights = ["#414868", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#c0caf5"]

[colors.tab_bar]
inactive_tab_edge = "#a0a0a0"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#7aa2f7"
bg_color = "#000000"

[colors.tab_bar.inactive_tab]
bg_color = "#a0a0a0"
fg_color = "#545c7e"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#a0a0a0"
fg_color = "#7aa2f7"

[colors.tab_bar.new_tab_hover]
fg_color = "#a0a0a0"
bg_color = "#7aa2f7"

[colors.tab_bar.new_tab]
fg_color = "#7aa2f7"
bg_color = "#191b28"

[metadata]
aliases = []
author = "folke"
name = "Tokyo Night Storm"